[package]
name = "photon"
version = "0.1.0"
authors = ["Michael", "Patrick"]
edition = "2018"
description = "Traces rays!"

[dependencies]
quick-xml = "0.15.0"
minifb = "0.12"
clap = "2.33.0"
png = "0.15.0"
